server:
  port: 3333

spring:
  application:
    name: gateway
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      - id: system
        uri: lb://system
        predicates:
        - Path=/system/**
        filters:
        - SwaggerHeaderFilter
        - StripPrefix=1

      - id: account
        uri: lb://account
        predicates:
        - Path=/account/**
        filters:
        - SwaggerHeaderFilter
        - StripPrefix=1


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/