swagger:
  basePackage: com.live.system.controller
  title: 系统模块文档
  description: 系统模块文档
  version: 1.0
spring:
  cloud:
    stream:
      bindings:
        myOutput:
          destination: wdtest_
          #content-type: application/json
        myInput:
          destination: wdtest_
          #content-type: application/json
          group: average
        myOutput2:
          destination: wdtest_2
          #content-type: application/json
        myInput2:
          destination: wdtest_2
          #content-type: application/json
          group: average
security:
  oauth2:
    resource:
      id: system
      user-info-uri: http://localhost:3333/auth/api/member
      prefer-token-info: false